### ISSUE TITLE
[Tool] Sprite Enhancements

### ISSUE THREAD

**Issue by BinaryConstruct** [TEdit/Terraria-Map-Editor#1273]
# Sprite Placement

- [ ] Find and Replace Sprites Styles #1033
- [x] Locate sprite on map #991
- [x] Place connected sprites, minecart track, platforms #554
  - [x] line drawing? #325
- [x] right click to pick sprite

# Sprite Picker
When searching it is not always clear that some items are hidden in different tiles, such as when searching for a particular set of furniture.

- [ ] Add a toggle box to enable aggregating all the subitems in the sprite search.
- [ ] Enable this toggle by default, and make the split-panel by tile view the option

# Sprite Bugs

- [ ] Music boxes missing, possible related to search?

**Comment by BinaryConstruct** [comment]
> The Sprite searching tool don't work for non-Steam games, wich is not very nice :'(
> Is it possible to adapt it, or to bring back the old one?

https://github.com/TEdit/Terraria-Map-Editor/wiki/Install-Requirements#for-sprite-viewing

**Comment by CommandCracker8** [comment]
Has this been implemented?

**Comment by BinaryConstruct** [comment]
Mostly, yes. Find and replace is not implemented.

**Comment by CommandCracker8** [comment]
Ah. It was the Find and Replace I needed.

**Comment by BinaryConstruct** [comment]
Added with [Tedit](https://github.com/TEdit/Terraria-Map-Editor/pull/2110) See https://docs.tedit.dev/
