### ISSUE TITLE
[Feature] Usability Improvements pt.2

### ISSUE THREAD

**Issue by BinaryConstruct** [TEdit/Terraria-Map-Editor#1274]
## Application
- [x] Splash screen
- [ ] Startup tips
- [x] links to wiki from help button or F1
- [x] automatic error reporting
- [x] load Steam cloud save files, or open the folder conveniently, somehow in the UI. #948
- [x] Better Zoom Control - zoom should keep tile under mouse cursor in same location instead of centering #919
- [x] Better world analysis/tally tabs.

## Tools
- [ ] Liquid masks #900
- [ ] pattern fill #826
- [x] Brush settings like, spray, hardness, patterns? etc. #1332
- [ ] Tile Search, Recently Used Tiles, Texture In selection window #1041
- [ ] allow tile masks to work when only editing extras like actuators
- [x] sprite eraser

**Comment by BinaryConstruct** [comment]
Progress update: Steam cloud saves done (5fc7d5a8). Remaining from this umbrella issue: masking system overhaul (decoupled masks, liquid masking), unified tile picker / pattern fill, startup tips, tile search/recently used.

**Comment by BinaryConstruct** [comment]
Closing this umbrella issue. Remaining work items have been split into dedicated issues for better tracking.
