### ISSUE TITLE
[Tool] Better Morph Tool

### ISSUE THREAD

**Issue by BinaryConstruct** [TEdit/Terraria-Map-Editor#533]
Use clentaminator morph algorithm?
http://terraria.gamepedia.com/Clentaminator

Rework morph tool 
- [ ] allow user customization of from-to tiles.
- [ ] preserve jungles when purifying corrupt/crimson
- [ ] add "tree" templates for morphing trees to random presets, using the root location of the tree and biome type/tree can grow on tile
- [ ] Ice Blocks and Special cave walls.
- [ ] Hardened sand
- [ ] Prevent Morph purify tool deleting anything on mannequins or item displays
- [ ] When I use the Morph tool to Purify the Corruption, it leaves the Corrupted Plants (24) still corrupted.
- [ ] converting crimson/corruption/hallow back to its natural form with that i have noticed when i convert an underground crimson biome to normal biome the cave decorations still are crimson #1053
- [ ] more morphs biomes #815 
- [ ] cleanse world button #913
- [ ] Use brush on area with "Hallowed Golf Grass" #1312
- [ ] isolate to just target biome (don't convert non-corrupt biomes) #1325
- [ ] Fix corrupted plants #1498
- [ ] Custom biomes (jungle, snow, hive, dungeon)

**Comment by enigmaquip** [comment]
I can work on this...... I don't usually use the morph tool, what use cases are there besides morphing from say crimson or corruption to clean blocks.

**Comment by BinaryConstruct** [comment]
> The morph tool does not allow for easy biome translation for Ice Blocks. (This is a link to the official terraria wiki page) These Types are as follows...
> 
> Corrupt Ice Biome - This usually produces a lot of Purple Ice blocks.
> Crimson Ice Biome -The main feature of this is Red Ice Blocks.
> Hallow Ice Biome - This features Pink Ice Block

**Comment by enigmaquip** [comment]
if we properly morph grass then the trees will morph properly.... the tree visual/wood gained from chopping is just based on the grass tile at the base of the tree.... on the tile side a tree is a tree is a tree :-)

**Comment by enigmaquip** [comment]
The problem I've noticed with morphing mushrooms is that a underground mushroom and a mushroom tree that is seen above ground are two separate entities.... The textures and UV's are ordered differently. If someone changed the base of a regular tree to mushroom grass it'll look fine, but if someone tried to convert tree tiles to a mushroom then the UV's will be incorrect and you'll get the errors seen in #767

**Comment by BinaryConstruct** [comment]
Tried to morph a portion of the Desert Underground to Crimson, but it won't morph stalactites and stalagmites like the stone and ice biomes do.

![54fbe6683845a3302cba04724613de37](https://user-images.githubusercontent.com/456755/32030561-594698fe-b9c1-11e7-86a5-fd83a3c6993f.png)

**Comment by BinaryConstruct** [comment]
## Merged Issues

### From #1824 — Masking for biome morph
There is no masking option for biome morphing. An example of an issue this causes is when trying to purify evil biomes it also changes mushroom biomes to jungle.

### From #1819 — Biome Morphing underground desert to Corruption/Crimson messes with cave deco sprites
When using the morph tool to apply corruption/crimson to an underground desert, certain rock decos are turned into ice or mushroom cave decos. This doesn't occur when morphing to hallow. Unchecking options such as base tiles, moss, evil or decorations also doesn't seem to make a difference.

![Screenshot 2022-12-16 202047](https://user-images.githubusercontent.com/74626960/208173461-f88f028b-3c9c-433d-b9bd-71e969c1702d.png)

![Screenshot 2022-12-16 202105](https://user-images.githubusercontent.com/74626960/208173479-b3203b90-5be2-440b-aca3-3ce9c98c8d6d.png)

**Comment by BinaryConstruct** [comment]
Moss plant growth added in 7af89d97: grows tile 184 sprites on exposed faces when morphing stone to moss, with correct V-axis anchoring and slope/half-block exclusion. MossBrick conversions were added in the prior commit.
